version: '3.9'

services:
  nginx:
    build: 
      context: ./var/docker/services/nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./var/docker/volumes/wordpress:/var/www/html
      # - ./var/docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env      
    depends_on:
      - php
      - mysql


  mysql:
    image: mysql:5.7
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./var/docker/volumes/mysql:/var/lib/mysql
    # networks:
    #   - app-network

  php:
    build: 
      context: ./var/docker/services/php/
      dockerfile: Dockerfile
    volumes:
      - ./var/docker/volumes/wordpress:/var/www/html
      - ./var/docker/volumes/shared:/var/www/shared

    env_file:
      - .env      
    # environment:
    #   WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    #   WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    #   WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    #   WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

  # docker compose run --rm wp_install /var/www/scripts/wp_install.sh
  # docker compose run --rm wp_install /var/www/scripts/fakerpress.sh
  wp_install:
    build: 
      context: ./var/docker/services/php/
      dockerfile: Dockerfile
    volumes:
      - ./var/docker/volumes/wordpress:/var/www/html
      - ./var/docker/volumes/shared:/var/www/shared
      # - ./var/docker/services/wp/scripts:/var/www/scripts
    depends_on:
      - nginx      
    entrypoint: ['/bin/ash']       #, '/var/www/wp_install.sh']
    env_file:
      - .env
      - ./var/lib/pw.env

  # docker compose run --rm wp_cmd user list
  # docker compose run --rm wp_cmd plugin install /var/www/plugins/pw_wp_importer.zip  --activate
  wp_cmd:
    build: 
      context: ./var/docker/services/php/
      dockerfile: Dockerfile
    volumes:
      - ./var/docker/volumes/wordpress:/var/www/html
      - ./var/docker/volumes/shared:/var/www/shared

      # - ./var/docker/services/wp/plugins:/var/www/plugins
      # - ./var/docker/volumes/wp/plugins:/var/www/plugins
      # - ./var/data:/var/www/data
      # - ./var/backup-prod:/var/www/backup-prod
    depends_on:
      - nginx      
    entrypoint: ['wp', '--allow-root']
    env_file:
      - .env
      - ./var/lib/pw.env

      