version: '3.9'

services:
  nginx:
    build: 
      context: ./docker/services/nginx/
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
      # - ./docker/services/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    # networks:
    #   - app-network

  mysql:
    image: mysql:5.7
    # ports:
    #   - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./docker/volumes/mysql:/var/lib/mysql
    # networks:
    #   - app-network

  php:
    build: 
      context: ./docker/services/php/
      dockerfile: Dockerfile
    volumes:
      - ./docker/volumes/wordpress:/var/www/html
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}

      