#!/bin/bash

PW_VAR_DIR=$BASEDIR"/var/"
PW_LIB_DIR=$PW_VAR_DIR"/lib/"

# Utils
PW_SSH_DIR=$PW_VAR_DIR"/.ssh/"
PW_TMP_DIR=$PW_VAR_DIR"/tmp/"

# Data, migrations
PW_DATA_DIR=$PW_VAR_DIR"/data/"

# Docker
PW_SERVICES_DIR=$PW_VAR_DIR"/docker/services/"
PW_VOLUMES_DIR=$PW_VAR_DIR"/docker/volumes/"

DOCKER_COMPOSE_YML=$BASEDIR/docker-compose.yml

# SHARED
PW_SHARED_DIR=$PW_VOLUMES_DIR"/shared/"

SFTP_KEY=$PW_VAR_DIR"/.ssh/id_rsa_dev"

PW_CONTAINER_SHARED_DIR="/var/www/shared/"
PW_CONTAINER_DATA_DIR=$PW_CONTAINER_SHARED_DIR"/data/"
PW_CONTAINER_SCRIPTS_DIR=$PW_CONTAINER_SHARED_DIR"/scripts/"
PW_CONTAINER_BACKUP_PROD_DIR=$PW_CONTAINER_SHARED_DIR"/backup-prod/"
PW_CONTAINER_PLUGINS_DIR=$PW_CONTAINER_SHARED_DIR"/plugins/"
PW_CONTAINER_THEMES_DIR=$PW_CONTAINER_SHARED_DIR"/themes/"



# write multiples lines to pw.env file 
echo "PW_CONTAINER_SHARED_DIR=$PW_CONTAINER_SHARED_DIR" > $PW_LIB_DIR"/pw.env"
echo "PW_CONTAINER_DATA_DIR=$PW_CONTAINER_DATA_DIR" >> $PW_LIB_DIR"/pw.env"
echo "PW_CONTAINER_SCRIPTS_DIR=$PW_CONTAINER_SCRIPTS_DIR" >> $PW_LIB_DIR"/pw.env"
echo "PW_CONTAINER_BACKUP_PROD_DIR=$PW_CONTAINER_BACKUP_PROD_DIR" >> $PW_LIB_DIR"/pw.env"
echo "PW_CONTAINER_PLUGINS_DIR=$PW_CONTAINER_PLUGINS_DIR" >> $PW_LIB_DIR"/pw.env"
echo "PW_CONTAINER_THEMES_DIR=$PW_CONTAINER_THEMES_DIR" >> $PW_LIB_DIR"/pw.env"
